In [1]:
import numpy as np

In [2]:
# Few Important Functions

In [3]:
# convert python list in a n dimensional array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a.shape

(5,)

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b.shape

(2, 4)

In [9]:
# for transpose the matrix

b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [10]:
# For dot product of two matrix

np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [12]:
# For generate a random  1D array 
# randint(low, high=None, size=None, dtype=int)

np.random.randint(60,100,10)

array([68, 77, 97, 82, 95, 72, 88, 88, 80, 65])

In [15]:
# For generate a random  2D array 
# randint(low, high=None, size=None, dtype=int)

np.random.randint(60,100,(5,5))

array([[96, 71, 73, 98, 99],
       [87, 61, 80, 85, 63],
       [95, 86, 68, 70, 90],
       [99, 90, 69, 97, 88],
       [74, 76, 94, 75, 96]])

In [16]:
# For find the maximum and minimum number from a matrix

matrix = np.random.randint(60,100,(5,5))

print(matrix)

print(np.max(matrix))

print(np.min(matrix))

[[90 61 95 73 75]
 [75 66 97 78 70]
 [95 88 64 90 76]
 [71 60 88 61 85]
 [93 94 64 83 82]]
97
60


In [18]:
# for find the minimum element's index from the given array

arr = np.array([0,1,2,-8,6,8,10])

np.argmin(arr)

3

In [22]:
# For find the unique elements from the given array and also counts the number 

arr = np.array([0,11,1,1,1,2,4,5,6,6,6,6,6,9,34,50,50,50])

np.unique(arr)    # it contains only the sorted array

array([ 0,  1,  2,  4,  5,  6,  9, 11, 34, 50])

In [25]:
# it sorted the unique elements and also return the counts of the elements in the array

u = np.unique(arr, return_counts = True)
print(u)

(array([ 0,  1,  2,  4,  5,  6,  9, 11, 34, 50]), array([1, 3, 1, 1, 1, 5, 1, 1, 1, 3]))


In [26]:
print(u[0])    # it containts the unique elements

[ 0  1  2  4  5  6  9 11 34 50]


In [27]:
print(u[1])    # it containts the counts of the same elements

[1 3 1 1 1 5 1 1 1 3]


In [28]:
# Program to find out the Number with the highest frequency in the array

arr = np.array([0,11,1,1,1,2,4,5,6,6,6,6,6,9,34,50,50,50])

u = np.unique(arr, return_counts = True)

idx = np.argmax(u[1])    # index with highest freq
elements = u[0][idx]     # element which have highest freq

print(elements)

6


In [29]:
# Slicing Arrays

matrix

array([[90, 61, 95, 73, 75],
       [75, 66, 97, 78, 70],
       [95, 88, 64, 90, 76],
       [71, 60, 88, 61, 85],
       [93, 94, 64, 83, 82]])

In [30]:
matrix[2:4,1:4]

array([[88, 64, 90],
       [60, 88, 61]])